version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
    restart: always
