version: '3.8'
services:
  wisdom-tmpv:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 990M
    restart: always
